In [6]:
#Vi_du 3.3.2.3
import numpy as np 
A=np.arange(10) 
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Vi_du 3.3.2.4
import numpy as np 
B=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]]) 
B

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [8]:
#Vi_du 3.3.2.5
arr=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) 
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#Vi_du 3.3.3.1
import numpy as np 
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]]) 
arr_view = arr_2d[:2, :2].view() 
print(arr_view) 

[[1 2]
 [4 5]]


In [10]:
#Vi_du 3.3.3.2
sub_arr=arr[:2,:2] 
print(sub_arr)

[[1 2]
 [4 5]]


In [6]:
#Vi_du 3.3.3.3
sub_arr_copy=arr[:2,:2].copy()  
print(sub_arr_copy)

[[1 2]
 [4 5]]


In [7]:
#Vi_du 3.3.3.4
arr=np.arange(1,10)           
grid= arr.reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#Vi_du 3.3.4.1
x = np.array([1, 2, 3]) 
y = np.array([4, 5, 6]) 
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [9]:
#Vi_du 3.3.4.2
import numpy as np 
a = np.array([[1, 2], 
              [3, 4]]) 
b = np.array([[5, 6], 
              [7, 8]]) 
# Kết hợp theo chiều đầu tiên (trục dọc/ trục 0) của mảng 
c = np.vstack((a, b))  
 
# Kết hợp theo chiều ngang (trục ngang/ trục 1) của mảng 
d = np.hstack((a,b)) 
print(c) 
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [10]:
#Vi_du 3.3.4.3
import numpy as np 
arr = np.arange(10)   
sub_arr1=np.split(arr,[3, 6])  
sub_arr2=np.split(arr,2)  
print("Mảng con sub_arr1 là:", sub_arr1, "\n") 
print("Mảng con sub_arr2 là:", sub_arr2)

Mảng con sub_arr1 là: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])] 

Mảng con sub_arr2 là: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [11]:
#Vi_du 3.3.4.4
import numpy as np 
arr = np.arange(16).reshape((4,4)) 
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
#Vi_du 3.3.5.2
arr = np.array([1, 2, 3, 4, 5]) 
new_element = 10 
index_to_insert = 2 
 
new_arr = np.insert(arr, index_to_insert, new_element) 
 
print(new_arr)

[ 1  2 10  3  4  5]


In [13]:
#Vi_du 3.3.6.1
arr = np.array([1, 2, 3, 4, 5]) 
indices = np.where(arr==3) 
indices

(array([2]),)

In [14]:
#Vi_du 3.3.6.3
arr = np.array([1, 5, 2, 3, 4]) 
max_idx = np.argmax(arr) 
min_idx = np.argmin(arr) 
 
print(max_idx) 
print(min_idx)

1
0


In [15]:
#Vi_du 3.3.7.1
arr = np.array([3, 1, 4, 2, 5]) 
idx_to_delete = 2                
new_arr=np.delete(arr,idx_to_delete) 
 
new_arr

array([3, 1, 2, 5])

In [16]:
#Vi_du 3.3.8.1
import numpy as np 
dtype = [('name', 'U20'), ('age', int), ('height', float)] 
data = np.array([('Minh', 22, 181.3), 
                 ('Lan', 40, 160.6), 
                 ('Linh', 31, 163.2), 
                 ('Lương',18,175.5), 
                 ('Thanh',50, 165.0)], dtype=dtype) 
 
print(data) 
 
print(data.dtype)

[('Minh', 22, 181.3) ('Lan', 40, 160.6) ('Linh', 31, 163.2)
 ('Lương', 18, 175.5) ('Thanh', 50, 165. )]
[('name', '<U20'), ('age', '<i8'), ('height', '<f8')]


In [17]:
#Vi_du 3.4.1
import numpy as np
import time
# Tạo một mảng NumPy với 100.000.000 phần tử
arr = np.arange(100000000, dtype=np.int64)
# Tính tổng các phần tử của mảng bằng vòng lặp
start_time = time.time()
total = np.int64(0)
for num in arr:
    total += num
end_time = time.time()
elapsed_time_loop = end_time - start_time
print("Tổng các phần tử mảng arr khi sử dụng vòng lặp:", total)
print("Thời gian (giây) khi sử dụng vòng lặp:", elapsed_time_loop)
# Tính tổng các phần tử của mảng bằng np.sum()
start_time = time.time()

total = np.sum(arr)

end_time = time.time()
elapsed_time_npsum = end_time - start_time

print("Tổng các phần tử mảng arr khi sử dụng hàm np.sum():", total)
print("Thời gian (giây) khi sử dụng np.sum():", elapsed_time_npsum)

num_times_faster = elapsed_time_loop / elapsed_time_npsum
print("Sử dụng vòng lặp chậm hơn là:", int(num_times_faster), "lần")

Tổng các phần tử mảng arr khi sử dụng vòng lặp: 4999999950000000
Thời gian (giây) khi sử dụng vòng lặp: 13.023722410202026
Tổng các phần tử mảng arr khi sử dụng hàm np.sum(): 4999999950000000
Thời gian (giây) khi sử dụng np.sum(): 0.05474591255187988
Sử dụng vòng lặp chậm hơn là: 237 lần


In [18]:
#Vi_du 3.4.2
import numpy as np
import timeit  # Import thư viện timeit để đo thời gian thực thi của các đoạn code.

# Tính tổng của mảng sử dụng Numpy
np_setup = "import numpy as np; np_array = np.arange(1, 1000001)"
np_code = "np_sum = np.sum(np_array)"
np_time = timeit.timeit(stmt=np_code, setup=np_setup, number=10)

# Tính tổng của danh sách sử dụng List
list_setup = "list_array = list(range(1, 1000001))"
list_code = "list_sum = sum(list_array)"
list_time = timeit.timeit(stmt=list_code, setup=list_setup, number=10)

print("Thời gian tính toán của Numpy:", np_time)
print("Thời gian tính toán của List:", list_time)

print("Numpy tính nhanh hơn List ở lượt chạy là ~", int(list_time / np_time), "lần!!")

Thời gian tính toán của Numpy: 0.008839399990392849
Thời gian tính toán của List: 0.08737399999517947
Numpy tính nhanh hơn List ở lượt chạy là ~ 9 lần!!


In [19]:
#Vi_du 3.4.3.1
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Phép Cộng: Sử dụng hàm np.add() hoặc toán tử '+'
Tong = np.add(arr1, arr2)
# hoặc Tong = arr1 + arr2

# Phép Trừ: Sử dụng hàm np.subtract() hoặc toán tử '-'
Hieu = np.subtract(arr1, arr2)
# hoặc Hieu = arr1 - arr2

# Phép Nhân: Sử dụng hàm np.multiply() hoặc toán tử '*'
Tich = np.multiply(arr1, arr2)
# hoặc Tich = arr1 * arr2

# Phép Chia: Sử dụng hàm np.divide() hoặc toán tử '/'
Thuong = np.divide(arr1, arr2)

print("Tổng của arr1 + arr2 là:", Tong)
print("Hiệu của arr1 - arr2 là:", Hieu)
print("Tích của arr1 * arr2 là:", Tich)
print("Thương của arr1 / arr2 là:", Thuong)

Tổng của arr1 + arr2 là: [5 7 9]
Hiệu của arr1 - arr2 là: [-3 -3 -3]
Tích của arr1 * arr2 là: [ 4 10 18]
Thương của arr1 / arr2 là: [0.25 0.4  0.5 ]


In [20]:
#Vi_du 3.4.3.3
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

# Căn bậc hai của các phần tử trong mảng
kq_can_hai = np.sqrt(arr)

# Lũy thừa 2 của các phần tử trong mảng
kq_luy_thua_2 = np.power(arr, 2)

# Logarit tự nhiên (cơ số e) của các phần tử trong mảng
kq_logarit = np.log(arr)

# Giá trị tuyệt đối của các phần tử trong mảng
kq_tri_tuyet_doi = np.abs(arr)

# Hàm logic NOT (đảo ngược giá trị) của các phần tử trong mảng
kq_not_logic = np.logical_not(arr)

# Hàm sin của các phần tử trong mảng
kq_sin = np.sin(arr)

print("Căn bậc hai của từng phần tử trong mảng là:", kq_can_hai)
print("Lũy thừa bậc hai của từng phần tử trong mảng là:", kq_luy_thua_2)
print("Logarit của từng phần tử trong mảng là:", kq_logarit)
print("Trị tuyệt đối của từng phần tử trong mảng là:", kq_tri_tuyet_doi)
print("Kết quả đảo ngược giá trị của các phần tử trong mảng là:", kq_not_logic)
print("Kết quả hàm sin của các phần tử trong mảng là:", kq_sin)

Căn bậc hai của từng phần tử trong mảng là: [1.         1.41421356 1.73205081 2.         2.23606798]
Lũy thừa bậc hai của từng phần tử trong mảng là: [ 1  4  9 16 25]
Logarit của từng phần tử trong mảng là: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Trị tuyệt đối của từng phần tử trong mảng là: [1 2 3 4 5]
Kết quả đảo ngược giá trị của các phần tử trong mảng là: [False False False False False]
Kết quả hàm sin của các phần tử trong mảng là: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [21]:
#Vi_du 3.4.4.3
import numpy as np
arr = np.array([0, 1, 2])
arr

array([0, 1, 2])

In [22]:
#Vi_du 3.4.4.4
import numpy as np
arr1 = np.arange(3)              # np.newaxis sử dụng để cho biết một chiều mới được thêm vào
arr2 = np.arange(3)[:, np.newaxis]  # Dấu hai chấm ':' cho biết tất cả các phần tử của chiều đầu tiên được giữ nguyên

print(arr1)
print(arr2)

[0 1 2]
[[0]
 [1]
 [2]]


In [4]:
#Vi_du 3.5.2
import numpy as np 
visitors = np.array([10200, 9875, 13567,7900,11200, 8871, 12567])
sum = 0 
for i in visitors: 
    if (i>10000): 
        sum+=i 
print(sum)

47534


In [5]:
#Vi_du 3.5.3
# Tạo mảng ngẫu nhiên 
arr1 = np.array([1, 2, 3, 4, 5]) 
arr2 = np.array([5, 4, 3, 2, 1]) 
 
# Toán tử so sánh dạng ufuncs 
result1 = arr1 > arr2   # Lớn hơn 
result2 = arr1 == arr2  # Bằng nhau 
result3 = arr1 <= arr2  # Nhỏ hơn hoặc bằng 
 
print("Kết quả lớn hơn:", result1)     
print("Kết quả bằng nhau:", result2)   
print("Kết quả nhỏ hơn hoặc bằng:", result3)

Kết quả lớn hơn: [False False False  True  True]
Kết quả bằng nhau: [False False  True False False]
Kết quả nhỏ hơn hoặc bằng: [ True  True  True False False]
